### ISSUE TITLE
Bug: lock slots on cargo wagon then view wagon inventory will cause items to spill to ground and break wagon icons (caused by Auto Sort Chests)

### ISSUE THREAD

**Issue by TheBloke** [Nexela/PickerInventoryTools#1]
Game version: 0.17.17
Mod: Picker Inventory Tools 1.0.0 + dependencies

Steps:
* Mod Settings->Automatically Sort Chests enabled
* Place some random items in a cargo wagon inventory
* Lock the slots using the red X, as seen here: 
![image](https://user-images.githubusercontent.com/784313/54845779-2e96f900-4cd2-11e9-9adb-2cd68ebbcb03.png)
* Close & re-open the wagon UI
* All contents spills to ground and the wagon now shows as empty, but the icons on the wagon still show as if it had contents:
![image](https://user-images.githubusercontent.com/784313/54845834-57b78980-4cd2-11e9-84a2-725fb0030c0f.png)

This does not happen with chests, only cargo wagons.

Disabling Automatically Sort Chests will prevent the problem from happening.

Discovered in my normal save, then re-created in a save containing only Inventory Tools plus its dependencies.  

Let me know if I can provide any further info, and thanks for all your great work on Picker*!

**Comment by TheBloke** [comment]
Further info: problem is caused by "Automatically sort chests".  Disabling this feature in Mod Settings prevents the problem.

I suppose it's also possible the bug is not in Picker Inventory Tools but in the game itself.  But I don't yet know enough about modding the game to know how to confirm that.  I thought I should raise it to you first given I have only experienced the issue with the mod and not in vanilla.

**Comment by TheBloke** [comment]
OK I've done a bit more digging and I do now think this must be a bug in the base game.

I can re-create it in a non-modded game by opening a cargo wagon where all slots are locked and then typing the following at console:

```/c local inventory = game.player.opened.get_inventory(defines.inventory.cargo_wagon) ;  inventory.sort_and_merge()```

I am going to close this issue and raise it on the forum.   Sorry to trouble you!

**Comment by Nexela** [comment]
Confirmed and fixed as a base game bug, Thank you for reporting it
