### ISSUE TITLE
Date or version info

### ISSUE THREAD

**Issue by LargePrime** [Nexela/PickerInventoryTools#10]
https://mods.factorio.com/mod/PickerInventoryTools/discussion/5e2fbb2e9be033000d27ba4b

You say "This will be fixed in the next release, Thank you", but, with no dates in the change log, (see https://mods.factorio.com/mod/PickerInventoryTools/changelog),  how do we know it is fixed?

**Comment by Nexela** [comment]
When the next release comes out!!!!!!  Working on deploy stuff that will remember to add the date to the changelog :)
