### ISSUE TITLE
[1.1.4] Error toggling Equipment

### ISSUE THREAD

**Issue by 0ptera** [Nexela/PickerInventoryTools#12]
Toggling night vision or personal defense produces the following error:
```
 428.498 Script @__stdlib__/stdlib/core.lua:46: LuaEquipment API call when LuaEquipment was invalid.
stack traceback:
	[C]: in function 'take'
	__PickerInventoryTools__/scripts/toggle-equipment.lua:55: in function 'swap_in_place'
	__PickerInventoryTools__/scripts/toggle-equipment.lua:97: in function <__PickerInventoryTools__/scripts/toggle-equipment.lua:64>
	[C]: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:354: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:437: in function <__stdlib__/stdlib/event/event.lua:388>
```

save file:
[PickerInventory Errors.zip](https://github.com/Nexela/PickerInventoryTools/files/4666321/PickerInventory.Errors.zip)

1x1 Night Vision ported over to 0.18:
[smallNightvision_1.1.0.zip](https://github.com/Nexela/PickerInventoryTools/files/4666320/smallNightvision_1.1.0.zip)

**Comment by Nexela** [comment]
Blame Rseding for changing the paramters for grid.take!
