### ISSUE TITLE
problem with copy chest content

### ISSUE THREAD

**Issue by szentigrad3** [Nexela/PickerInventoryTools#3]
https://puu.sh/DAIdX/60d009607b.jpg

**Comment by Nexela** [comment]
Thanks for the report!
Fixed for the next release. As it is only a minor bug that only happens when trying to paste without a chest saved and doesn't affect anything else I am not going to do a release right away

**Comment by szentigrad3** [comment]
i was trying to copy a warehouse to a warehouse and it came up with that problem, i downloaded your fix and i can't move the contents of one chest to another at all, just says no container selected
