### ISSUE TITLE
move chest contents

### ISSUE THREAD

**Issue by szentigrad3** [Nexela/PickerInventoryTools#4]
Thanks for the report!
Fixed for the next release. As it is only a minor bug that only happens when trying to paste without a chest saved and doesn't affect anything else I am not going to do a release right away

_Originally posted by @Nexela in https://github.com/Nexela/PickerInventoryTools/issues/3#issuecomment-498065714_

i was trying to copy a warehouse to a warehouse and it came up with that problem, i downloaded your fix and i can't move the contents of one chest to another at all, just says no container selected

**Comment by Nexela** [comment]
Ok, its not fixed......
I have it fixed locally but there is some logic I don't like around using cut/paste as the same keybind

**Comment by Nexela** [comment]
I should have this really fixed this weekend, Thank you for your patience!

**Comment by Nexela** [comment]
This should be fixed in e4bd8cc7503d12e7f71fe145944619d32094e817 
Let me know how it works for you!

**Comment by szentigrad3** [comment]
works perfect thanks
