### ISSUE TITLE
Conflict with Auto Stock and AutoTrash

### ISSUE THREAD

**Issue by Choumiko** [Nexela/PickerInventoryTools#6]
There is a minor conflict/unexpected behaviour if the Auto stock setting is true and my AutoTrash mod is installed and the user isn't aware of that setting defaulting to true.
Both change request/trash slots on different events which can lead to some confusion
(https://forums.factorio.com/viewtopic.php?p=439607#p439417)

Quickest solution is probably to set it to false if AutoTrash is installed/gets added to a save. And maybe hide the setting in the settings stage (i think we have access to installed mods there? not sure)

I think i could do it all on my side, but changing mod settings from another mod is something that makes me slightly uncomfortable and if you add a new setting that conflicts with Autotrash i'd have to update again.

Feel free to ping me on discord

**Comment by Nexela** [comment]
I will set it up so detection of autotrash disables these.   Because autotrash > these and these still have issues.
