### ISSUE TITLE
picker-autodeconstruct-target should not deconstruct elements that are still valid targets

### ISSUE THREAD

**Issue by weaselp** [Nexela/PickerInventoryTools#7]
I do bot based mining, and sometimes more than one drill delivers to a box.  I have both picker-autodeconstruct and picker-autodeconstruct-target enabled.

Now, when a drill runs out of resources, the target box gets marked for deconstruction even if another drill still mines into it.

It would be nice if auto-deconstruct could check for this case and not mark items for descrution when they are still targets of not-yet-to-be-deconstructed drills.

**Comment by Nexela** [comment]
It shouldn't mark the box if there is more than one miner mining into it.   Can you post a BP that this happens with?

**Comment by weaselp** [comment]
Sure,

here's a blueprint string: https://volatile.noreply.org/2019-07-21-ziPGDn78GXM/mine.bp
and here's two images, before and after a drill gets exhausted:
https://volatile.noreply.org/2019-07-21-XQb82PVJyzI/m01.jpg
https://volatile.noreply.org/2019-07-21-XQb82PVJyzI/m02.jpg

This is in 0.17.58 and picker inventory tools 1.0.2.

Cheers
